= Wat Manual
:author: Luke Gessler
:lang: en
:encoding: UTF-8
:doctype: book
:toc: left
:toclevels: 3
:sectlinks:
:sectanchors:
:leveloffset: 1
:sectnums:
:imagesdir: img/src
:imagesoutdir: img/out
:favicon: favicon.ico
:hide-uri-scheme: 1

= Introduction

WAT (**W**ord **A**lignment **T**ool is an app for annotating word alignments in aligned sentences.

== Installation

1. Provision a server that will run the app. We will assume you are using an Ubuntu machine. If you are the only one annotating, you may also run the server locally.
2. Download https://github.com/lgessler/wat/releases[a JAR from the latest release].
3. https://dzone.com/articles/run-your-java-application-as-a-service-on-ubuntu[Configure the JAR as a service]. You may also just run the app by typing `java -jar wat-{version-info}.jar` into the command line.
4. If you are not running WAT locally, set up HTTPS. **If you do not set up HTTPS, your instance will be vulnerable to password-stealing attacks.** Fortunately, this is fairly easy--we recommend running this program on the default port (8080) and using a reverse proxy like Nginx with https://certbot.eff.org/[certbot] to provide HTTPS.

== First Login
Navigate to the app, e.g. `http://localhost:8080`.
Register for an account, and note that *the first user registered will have admin privileges*.
You should do this step before making your instance of WAT visible to the internet.

== Example Project
Now, click the button in the top left, and hit "Admin Settings".
Here, you create user accounts and projects.
A project is a collection of documents that you will be annotating, and by default, non-admin users may not see or edit them.
Users may be granted access under the Project Management activity.

For now, create a project, then use the button in the top left again to go to "Projects".
Click on your project.
Click on the "Add Document" button.
Choose a name for the document, and copy-paste the following text into the fields:

```
# Target Sentences:
ʕAt’id-a nesi-q kinaw r-oq-ru łina-łay esi-n
Ražbadin-z idu baru-n xexbi-n yoł-ƛin žawab teƛ-n ečru-ni žek’u-a

# Target Glosses:
Atid-ERG DEM1.ISG.OBL-POSS.ESS entire IV-happen-PST.PRT what.OBL-CONT.ABL tell-PST.UNW
Razhbadin-GEN2 home wife-and children-and be-QUOT answer give-PST.UNW old-DEF man-ERG

# Translation Sentences:
Atid told about everything that had happened to him.
"His wife and children live at Razhbadin's home", answered the old man.
```

These fields all contain tokens which must be whitespace-tokenized, and the `Sentences` and `Glosses` fields must contain the same number of tokens in each sentence.
The `Glosses` field allows you to add additional information about the sentence, e.g. with interlinear glosses, and you may add potentially many glosses by separating the gloss sets with two newlines.
So, this input would also be valid:

```
# Target Sentences:
ʕAt’id-a nesi-q kinaw r-oq-ru łina-łay esi-n
Ražbadin-z idu baru-n xexbi-n yoł-ƛin žawab teƛ-n ečru-ni žek’u-a

# Target Glosses:
Atid-ERG DEM1.ISG.OBL-POSS.ESS entire IV-happen-PST.PRT what.OBL-CONT.ABL tell-PST.UNW
Razhbadin-GEN2 home wife-and children-and be-QUOT answer give-PST.UNW old-DEF man-ERG

Atid-ERG DEM1.ISG.OBL-POSS.ESS entire IV-happen-PST.PRT what.OBL-CONT.ABL tell-PST.UNW
Razhbadin-GEN2 home wife-and children-and be-QUOT answer give-PST.UNW old-DEF man-ERG

# Translation Sentences:
Atid told about everything that had happened to him.
"His wife and children live at Razhbadin's home", answered the old man.
```

Now, hit "Create Document" and open the document, which you should now see in the project's document list.
In the "Align" tab, you may click on sentences and make alignments between them by clicking and dragging on words.

In the "Settings" tab, you may change the document's name or delete the document.
Additionally, you may export it into a .json representation in order to obtain the alignments.
Note that *each user has a separate set of alignments for a document*, so when using this file, be sure to use the right user's alignments.
In the future, we may add features for adjudication, etc.

= Developer's Guide

First, take care of dependencies. You will need to:

1. https://clojure.org/guides/getting_started[Install Clojure CLI tools]
2. https://nodejs.org/en/download/[Install NPM and Node]
3. https://yarnpkg.com/getting-started/install[Install Yarn]

== Running: Command Line
```bash
# install dependencies
$ yarn
# start compiling CLJS--leave this running in a terminal session...
$ yarn client
# and in a separate session, start a server repl--note you'll have to type `(start)`
$ yarn server
clojure -A:dev
Clojure 1.10.1
user=> (start)
# navigate to localhost:8085, and see package.json for more
```

## Running: IntelliJ + Cursive
On the terminal:
```bash
yarn client
```

Clojure Server Profile:

1. Make a new profile based on "Clojure REPL > Local"
2. Select "Run with Deps"
3. Put `dev` in Aliases
4. Run and write (start)
5. See `src/dev/user.clj` for development tools.

ClojureScript Client Profile:

1. Make a new profile based on "Clojure REPL > Remote"
2. Connection type: `nREPL`
3. Connection details: "Use port from nREPL file"
4. Project: `wat`
5. Make sure you're entered `(start)` in the server.
6. Navigate to `localhost:8085`
7. Run your client profile and enter:
```clojure
(require '[shadow.cljs.devtools.api :as shadow])
(shadow/repl :main)
```
8. Write `(js/console.log "hi")` and ensure that it was printed out to the console in your browser session

## Yarn Commands

*Note*: all `docs` command will require additional dependencies for `asciidoctor`. Use `gem` to get them.

* **`client`**: Start the shadow-cljs ClojureScript compiler, which will compile code to JS and also hot reload any changes.
* `client/cljs-repl`: Get a client CLJS REPL (note: requires a running browser session).
* `client/clj-repl`: Get a client CLJ REPL (note: this is only useful if you want to fiddle with shadow-cljs, which is rare).
* **`server`**: Start a server REPL. (This will not start the server automatically--to do that, you need to type `(start)`.)
* **`start`**: Convenience function for running `client/main` and `server`.
* `clean`: Remove all compilation artefacts.
* `client/release`: Build the single `.js` bundle for a production release.
* `server/release`: Build the single `.jar` file for a production release.
* `release`: Convenience function for running `client/release` and `server/release`.
* `test`: Run all Clojure tests. (Currently, there are no CLJS tests.)
* `clojure-outdated`: Check Clojure dependencies for oudatedness.
* `npm-outdated`: Check NPM dependencies for outdatedness.
* `loc`: Count lines of code (requires `cloc`: `npm install -g cloc`).
* `docs/html`: Compile `docs/book.adoc` into HTML at `target/book.html`
* `docs/pdf`: Compile `docs/book.adoc` into a PDF at `target/book.pdf`
* `docs`: Perform `docs/html` and `docs/pdf`
